FROM nimlang/nim:2.2.10

RUN git clone --depth 1 --branch v0.5.0 \
      https://github.com/puffball1567/flowbrigade.git /deps/flowbrigade \
    && git clone --depth 1 --branch v0.4.0 \
      https://github.com/puffball1567/nifkit.git /deps/nifkit \
    && git clone --depth 1 --branch v0.2.0 --recurse-submodules \
      https://github.com/status-im/nim-zlib.git /deps/zlib \
    && git clone --depth 1 --branch v0.5.1 \
      https://github.com/status-im/nim-stew.git /deps/stew \
    && git clone --depth 1 --branch v0.5.1 \
      https://github.com/arnetheduck/nim-results.git /deps/results \
    && git clone --depth 1 --branch v0.2.5 \
      https://github.com/status-im/nim-unittest2.git /deps/unittest2 \
    && git clone https://github.com/Araq/libcurl.git /deps/libcurl \
    && cd /deps/libcurl \
    && git checkout v1.0.0 \
    && git clone https://github.com/status-im/nim-faststreams.git /deps/faststreams \
    && cd /deps/faststreams \
    && git checkout 50889cd16ec8771106cdd0eeea460039e8571e06 \
    && git clone --depth 1 --branch v0.5.3 \
      https://github.com/status-im/nim-serialization.git /deps/serialization \
    && git clone --depth 1 --branch v0.4.2 \
      https://github.com/vacp2p/nim-cbor-serialization.git /deps/cbor_serialization \
    && git clone https://github.com/status-im/nim-protobuf-serialization.git \
      /deps/protobuf_serialization \
    && cd /deps/protobuf_serialization \
    && git checkout 24ddb65800b351268412840b19a33c6b61bb3046 \
    && git clone --depth 1 --branch 1.3.0 \
      https://github.com/zevv/npeg.git /deps/npeg

WORKDIR /workspace/joubako
COPY . .

ARG JOUBAKO_MEMORY_MANAGER=arc

RUN JOUBAKO_DEPENDENCY_ROOT=/deps nim r \
      --out:/tmp/joubako-write-ci-paths .github/write_ci_paths.nim \
    && nim c -d:release --mm:${JOUBAKO_MEMORY_MANAGER} \
      --out:/usr/local/bin/joubako-e2e tests/e2e/client.nim

CMD ["/usr/local/bin/joubako-e2e"]
